# Generated by Django 5.0.6 on 2025-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
