# Generated by Django 5.0.6 on 2025-02-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0003_module_user_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="rating.user"
            ),
            preserve_default=False,
        ),
    ]
