# Generated by Django 5.0.6 on 2025-02-12 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0004_rating_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="module",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="professors",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="year",
        ),
        migrations.CreateModel(
            name="ModuleInstance",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("semester", models.IntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rating.module"
                    ),
                ),
                ("professors", models.ManyToManyField(to="rating.professor")),
            ],
        ),
        migrations.AddField(
            model_name="rating",
            name="moduleInstance",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rating.moduleinstance",
            ),
            preserve_default=False,
        ),
    ]
