# Generated by Django 5.0.6 on 2025-02-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0005_remove_rating_module_remove_rating_professors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleinstance",
            name="professors",
        ),
        migrations.AddField(
            model_name="rating",
            name="professor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rating.professor",
            ),
            preserve_default=False,
        ),
    ]
