# Generated by Django 5.0.6 on 2025-02-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rating", "0006_remove_moduleinstance_professors_rating_professor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="moduleInstance",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="professor",
        ),
        migrations.CreateModel(
            name="TaughtModule",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "moduleInstance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rating.moduleinstance",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rating.professor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rating",
            name="TaughtModule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rating.taughtmodule",
            ),
            preserve_default=False,
        ),
    ]
