# Generated by Django 4.2 on 2025-02-15 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rating",
            "0007_remove_rating_moduleinstance_remove_rating_professor_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="TaughtModule",
            new_name="taughtModule",
        ),
    ]
